translate useRef hook
reactjs/tr.react.dev pull request #407
Opened 2023-04-26 17:18 UTC by coskuncakir

2023-04-26 17:43 UTC, alioguzhan requested changes
Tesekkurler. Birkac nokta var. Sonrasinda merge edebiliriz.

2023-04-26 17:43 UTC, alioguzhan commented on src/content/reference/react/useRef.md
> +* `initialValue`: Ref nesnesinin `current` özelliğinin başlangıçta ne olmasını istediğiniz değer. Herhangi türde bir değer olabilir. Bu argüman, ilk render işleminden sonra göz ardı edilir.
`ne` kelimesine gerek yok sanirim burada.

2023-04-26 17:43 UTC, alioguzhan commented on src/content/reference/react/useRef.md
> +#### Döndürür {/*returns*/}
Bu da OK; ama sanki `Geri Donus Degeri` yazsak daha aciklayici olur gibi. Yine de karar sizin burada.

2023-04-26 17:43 UTC, alioguzhan commented on src/content/reference/react/useRef.md
> +* Strict Mode'da, React [istenmeyen yan etkileri bulmanıza yardımcı olmak için](#my-initializer-or-updater-function-runs-twice) **bileşeninizi iki kez çağıracaktır.** Bu sadece geliştirme ortamı için
`bu davranışı etkilememelidir` -> `bu, davranışı etkilememelidir`

2023-04-26 17:43 UTC, alioguzhan commented on src/content/reference/react/useRef.md
> +Bir sonraki render işlemlerinde, `useRef` aynı nesneyi döndürecektir. `current` özelliğini değiştirerek bilgi saklayabilir ve daha sonra okuyabilirsiniz. Bu size [state](/reference/react/useState) öz
`Bir sonraki render işlemlerinde` -> `Sonraki render işlemlerinde`

2023-04-26 17:43 UTC, alioguzhan commented on src/content/reference/react/useRef.md
> + <Recipes titleText="useRef ile DOM'u manipüle etme örnekleri" titleId="examples-dom">
extra space var sanirim burada.

2023-04-26 17:43 UTC, alioguzhan commented on src/content/reference/react/useRef.md
> +Normalde, render sırasında `ref.current` yazmaya veya okumaya izin verilmez. Ancak bu senaryoda sorun yoktur çünkü sonuç her zaman aynıdır ve koşul sadece başlatma sırasında çalışır, bu nedenle tamam
`öngörülebilir` -> `öngörülebilirdir`

2023-04-26 20:09 UTC, coskuncakir commented
@alioguzhan cok tesekkurler review icin, belirttiginiz noktalara hak verdim ve guncelledim o sekilde. Bir de ilk cumle icime sinmemisti ufak bir degisiklik yaptim, yorumunuz olursa konusuruz yine.

2023-04-27 10:38 UTC, alioguzhan approved these changes
Tesekkurler!

2023-04-27 10:41 UTC, merged