Translate `createContext`
reactjs/tr.react.dev pull request #409
Opened 2023-04-27 06:46 UTC by halilatilla

Translate `createContext`

2023-04-28 13:35 UTC, alioguzhan requested changes
Tesekkurler. Birkac nokta var. Sonrasinda merge edebiliriz.

2023-04-28 13:35 UTC, alioguzhan commented on src/content/reference/react/createContext.md
> +* `defaultValue`: Context'i okuyan bileşenlerin üzerinde eşleşen bir context sağlayıcısı olmadığında contextin sahip olmasını istediğiniz değer. Anlamlı bir varsayılan değeriniz yoksa, `null` belirti
`Statik` -> `Statiktir`

2023-04-28 13:35 UTC, alioguzhan commented on src/content/reference/react/createContext.md
> +**Context nesnesi kendisi herhangi bir bilgi içermez.** Diğer bileşenlerin _hangi_ contexti okuyacağını veya sağlayacağını temsil eder. Genellikle, context değerini belirtmek için bileşenin üstünde [
`Context nesnesi kendisi` -> `Context nesnesinin kendisi` sanki daha iyi gibi.

2023-04-28 13:35 UTC, alioguzhan commented on src/content/reference/react/createContext.md
> +Bu eski yöntem hala çalışıyor olsa da, **yeni yazılan kodun contextini [`useContext()`](/reference/react/useContext) ile okunması daha uygundur:**
`contextini` -> `contextinin` 

ya da 

`okunması` -> `okumak`

2023-04-28 13:35 UTC, alioguzhan commented on src/content/reference/react/createContext.md
> +Context, bileşenlerin [bilgiyi derinlemesine aktarmasına](/learn/passing-data-deeply-with-context) olanak tanır ve açıkça prop'lar geçirmeden yapar.
`prop'lar` -> `prop'lari`

ya da

`prop'lar` -> `prop`

2023-04-28 13:35 UTC, alioguzhan commented on src/content/reference/react/createContext.md
> +Şimdi `Page` bileşeni ve içindeki herhangi bir bileşen, ne kadar derin olursa olsun, iletilen context değerlerini "görecek" ve iletilen context değerleri değişirse, React contexti okuyan bileşenleri
`reder` -> `render`

2023-04-28 16:52 UTC, halilatilla commented on src/content/reference/react/createContext.md
> +**Context nesnesi kendisi herhangi bir bilgi içermez.** Diğer bileşenlerin _hangi_ contexti okuyacağını veya sağlayacağını temsil eder. Genellikle, context değerini belirtmek için bileşenin üstünde [
done ✅

2023-04-28 16:52 UTC, halilatilla commented on src/content/reference/react/createContext.md
> +Bileşenlerinizin bir context sağlayıcısı ile sarmalayarak içindeki tüm bileşenler için bu contextin değerini belirtin:
done ✅

2023-04-28 16:53 UTC, halilatilla commented on src/content/reference/react/createContext.md
> +Bu eski yöntem hala çalışıyor olsa da, **yeni yazılan kodun contextini [`useContext()`](/reference/react/useContext) ile okunması daha uygundur:**
done ✅

2023-04-28 16:53 UTC, halilatilla commented on src/content/reference/react/createContext.md
> +Context, bileşenlerin [bilgiyi derinlemesine aktarmasına](/learn/passing-data-deeply-with-context) olanak tanır ve açıkça prop'lar geçirmeden yapar.
done ✅

2023-04-28 16:53 UTC, halilatilla commented on src/content/reference/react/createContext.md
> +Şimdi `Page` bileşeni ve içindeki herhangi bir bileşen, ne kadar derin olursa olsun, iletilen context değerlerini "görecek" ve iletilen context değerleri değişirse, React contexti okuyan bileşenleri
done ✅

2023-04-28 18:03 UTC, alioguzhan commented on src/content/reference/react/createContext.md
> +Bu eski yöntem hala çalışıyor olsa da, **yeni yazılan kodun contextini [`useContext()`](/reference/react/useContext) ile okunması daha uygundur:**
typo olmus sanirim. `okunmak` yaziyor su anda. `okumak` olacakti.

2023-04-29 10:04 UTC, halilatilla commented on src/content/reference/react/createContext.md
> +Bu eski yöntem hala çalışıyor olsa da, **yeni yazılan kodun contextini [`useContext()`](/reference/react/useContext) ile okunması daha uygundur:**
upps, sorry :)
done✅

2023-04-29 10:56 UTC, alioguzhan approved these changes
Tesekkurler!

2023-04-29 10:58 UTC, merged