fragment full translation
reactjs/tr.react.dev pull request #419
Opened 2023-05-01 23:06 UTC by K2adir

2023-05-01 23:06 UTC, K2adir commented
.

2023-05-02 03:49 UTC, alioguzhan requested changes
Tesekkurler. Birkac nokta var.  Sonrasinda merge edebiliriz.

2023-05-02 03:49 UTC, alioguzhan commented on src/content/reference/react/Fragment.md
> +<Fragment>, genellikle <>...</> sözdizimiyle birlikte kullanılır ve bir kaplayıcı düğüm olmadan elemanları gruplamaya olanak tanır.
backtickleri koymak gerekir buraya. (`<Fragment>` ve `<>..</>` kisimlarina)

Sadece burada degil bircok yerde koyulmamis sanirim.

2023-05-02 03:49 UTC, alioguzhan commented on src/content/reference/react/Fragment.md
> +isteğe bağlı `anahtar`: Açık <Fragment> sözdizimiyle tanımlanan Fragment'ler syntax may have [anahtara](/learn/rendering-lists#keeping-list-items-in-order-with-key) sahip olabilir.
`syntax may have` kismi cevrilmemis sanirim.

2023-05-04 01:08 UTC, K2adir reviewed
highlighted errors revised

2023-05-04 06:06 UTC, merged