translate uselayouteffect reference
reactjs/tr.react.dev pull request #420
Opened 2023-05-02 15:18 UTC by baspinarenes

2023-05-02 15:36 UTC, baspinarenes commented
"Troubleshooting" kavramını sorun giderme olarak çevirdim ama içime pek sinmedi. Daha iyi öneri varsa değiştirebiliriz.

2023-05-02 20:05 UTC, alioguzhan requested changes
Tesekkurler. Bir nokta var sadece. Gozden kacmis sanirim.  Sonrasinda merge edebiliriz.

2023-05-02 20:05 UTC, alioguzhan commented on src/content/reference/react/useLayoutEffect.md
> +## Sorun giderme {/*troubleshooting*/}
Bence gayet guzel. Direkt anlami zaten. 👍🏼

2023-05-03 06:02 UTC, baspinarenes commented on src/content/reference/react/useLayoutEffect.md
> +* **isteğe bağlı** `dependencies`: Kurulum fonksiyonu içerisinde başvurulan reaktif değerlerin listesidir. Reaktif değerler; prop'lar, state'ler ve de bileşenin içerisinde tanımlanan değişkenler ve f
Burayı çevirebilmemiz için koddaki parametre adını da türkçeye çevirmemiz gerekecek. Bence kodda çeviri olmamalı ancak dediğiniz şekilde düzeltme yaptım.

2023-05-03 06:18 UTC, alioguzhan commented on src/content/reference/react/useLayoutEffect.md
> +* **isteğe bağlı** `dependencies`: Kurulum fonksiyonu içerisinde başvurulan reaktif değerlerin listesidir. Reaktif değerler; prop'lar, state'ler ve de bileşenin içerisinde tanımlanan değişkenler ve f
Ben eksik ifade ettim sanirim. Kod kismini degistirmenize gerek yoktu. parantez icinde ingilizcesini de tutarak oraya referans verebiliriz. Bence kod kismini geri alalim. sadece  

**isteğe bağlı** `dependencies` -> **isteğe bağlı** `bagimliliklar (dependencies)`

seklinde yazabiliriz. Cunku diger yerlerde `bagimlilik` kelimesini kullanmissiniz zaten. Tutarli olmasi acisindan demistim ben. Tesekkurler.

2023-05-03 07:50 UTC, alioguzhan requested changes

2023-05-03 07:50 UTC, alioguzhan commented on src/content/reference/react/useLayoutEffect.md
> +useLayoutEffect(kurulum, bağımlılıklar?)
burayi

2023-05-03 07:50 UTC, alioguzhan commented on src/content/reference/react/useLayoutEffect.md
> +### `useLayoutEffect(kurulum, bağımlılıklar?)` {/*useinsertioneffect*/}
ve burayi geri alabiliriz. alttaki degisiklik kalabilir. merge edelim sonrasinda.

2023-05-04 16:48 UTC, alioguzhan approved these changes
Tesekkurler

2023-05-04 16:48 UTC, merged