Translate conditional rendering
reactjs/tr.react.dev pull request #421
Opened 2023-05-02 15:23 UTC by serkanisyapan

Translate `Conditional Rendering` page.

2023-05-02 15:26 UTC, serkanisyapan commented
Bileşen isimlerini Türkçe'ye çevirmedim ama çeviriyorsak onları ekleyebilirim. `Rendering Lists` sayfasında da çevirebilirim.

2023-05-02 16:25 UTC, alioguzhan requested changes
Tesekkurler. Bazi yerleri belirttim. Uzerlerine konusabiliriz isterseniz. Sonrasinda merge edebiliriz.

2023-05-02 16:25 UTC, alioguzhan commented on src/content/learn/conditional-rendering.md
> +Diyelim ki elinizde birden çok `Item` render eden bir `PackingList` bileşeni var, ve `Item`'lar bavula konulup konulmadıklarına göre işaret almışlar:
Diyelim ki elinizde bir `PackingList` bileşeni var. Bu bilesen, bavula konulup konulmadıklarına gore isaretlenebilen, `Item` bileseninden birkac tane render ediyor:

hatta: 

Diyelim ki bavula konulup konulmadıklarına göre (`isPacked`) işaretlenebilen `Item` bileseninden birkac tane render eden bir `PackingList` bileşeniniz var:

---

bu tarz bi'sey daha iyi olabilir sanki.  Cunku isaret almis olmalarindan ziyade isaretlenebileceklerini belirtiyor cumlede.

2023-05-02 16:25 UTC, alioguzhan commented on src/content/learn/conditional-rendering.md
> +Her iki koşulda `<li className="item">...</li>` ifadesini döndürmekte:
`Her iki koşulda` -> `Her iki koşul da`

2023-05-02 16:25 UTC, alioguzhan commented on src/content/learn/conditional-rendering.md
> + Bu kodu şöyle okuyabilirsiniz: *"eğer `isPacked` prop'u true (doğru) ise, o zaman (`?`) `name + ' ✔'` render et, aksi halde (`:`) `name` render et"*.
basta extra bi space var sanirim.

2023-05-02 16:25 UTC, alioguzhan commented on src/content/learn/conditional-rendering.md
> +Bu syntax en ayrıntılı ama aynı zamanda en esnek olanıdır. Aşağıda nasıl çalıştığını görebilirsiniz:
`style` icin burada  `tarz` ya da `yontem` daha dogru olabilir.

2023-05-02 16:25 UTC, alioguzhan commented on src/content/learn/conditional-rendering.md
> +Eğer JavaScript diline aşina değilseniz, bu çeşitli syntax'ler ilk başta kafa karıştırıcı olabilir. Ancak bunları öğrenmek, sadece React bileşenleri değil, herhangi bir JavaScript kodunu okumanıza ve
ayni sekilde de burada da: `bu cesitli stiller` ya da `bu cesitli yontemler` hatta `bu yontem cesitliligi` bile olabilir. Nasil uygun gorurseniz.

2023-05-03 07:40 UTC, serkanisyapan commented
> bir de, bir satirda conflict var sanirim. upstreamden guncelleme gelmisti bu dosyaya. onlar cakisiyor sanirim.

Teşekkürler, gerekli değişiklikleri yaptım. Conflict sorununu da çözdüm sanırım. Bu konularda yeniyim bir yanlışlık olmamıştır umarım.

2023-05-03 07:54 UTC, alioguzhan approved these changes
Tesekkurler. Conflict de cozulmus gozukuyor. Merge ediyorum

2023-05-03 07:55 UTC, merged