Option translated -
reactjs/tr.react.dev pull request #435
Opened 2023-05-06 01:07 UTC by K2adir

2023-05-06 21:24 UTC, alioguzhan commented
Preview deploymenti basarisiz olmus. Bir yerde bir hata olabilir. Localde sitenin calisip calismadigini kontrol edebilir misiniz bu branchta ? Tesekkurler.

2023-05-07 02:49 UTC, K2adir commented
fragment.md file had an issue with an extra backtick, fixing that, resolved the problem with the option.md file. 
tested on the browser, double-checked with the English doc. All tests passed.

2023-05-07 16:32 UTC, alioguzhan requested changes
Tesekkurler. Bir iki nokta var sadece. sonrasinde merge edebiliriz.

2023-05-07 16:32 UTC, alioguzhan commented on src/content/reference/react-dom/components/option.md
> +[Web Tarayıcısının`<option>` bileşeni](m5bilisim.com/webokulu/etiketler/etiket-option.php) [`<select>`](/reference/react-dom/components/select) kutusunun içinde bir seçenek oluşturmanıza olanak tanır
buradaki link calismiyor. basina protocol bilgisi de eklenmesi lazim sanirim. 

ama onun disinda, kaynak gosterilen sayfa ne kadar guncel ve dogru bilgi iceriyor emin degilim. HTML standart elemanlariyla ilgili oldugu icin bence direkt olarak mozilla sitelerini birakabiliriz link olarak. Cunku Web elemanlarina yeni ozellikler eklenip cikabiliyor. Yanlis / outdated bir kaynak vermis olmayalim. 

O yuzden buradaki ve diger yerlerdeki link degisikliklerini geri alabiliriz.

2023-05-07 16:32 UTC, alioguzhan commented on src/content/reference/react-dom/components/option.md
> +### Seçenekler İçeren Bir Seçim Kutusu Gösterme {/*displaying-a-select-box-with-options*/}
Sadece ilk kelimeyi capitalized yapalim bence. tutarli olmus olur diger yerler ile.

2023-05-08 06:27 UTC, alioguzhan commented on src/content/reference/react-dom/components/option.md
> +[Web Tarayıcısının`<option>` bileşeni](m5bilisim.com/webokulu/etiketler/etiket-option.php) [`<select>`](/reference/react-dom/components/select) kutusunun içinde bir seçenek oluşturmanıza olanak tanır
5-6 yerde daha var sanirim ayni siteye referans. MDN linkerini komple oldugu gibi birakabiliriz.

2023-05-09 03:38 UTC, K2adir commented on src/content/reference/react-dom/components/option.md
> +[Web Tarayıcısının`<option>` bileşeni](m5bilisim.com/webokulu/etiketler/etiket-option.php) [`<select>`](/reference/react-dom/components/select) kutusunun içinde bir seçenek oluşturmanıza olanak tanır
@alioguzhan orijinal linkler geri eklendi

2023-05-09 05:51 UTC, alioguzhan approved these changes
Tesekkurler!

2023-05-09 05:51 UTC, merged