translate `Extracting State Logic into a Reducer`
reactjs/tr.react.dev pull request #446
Opened 2023-05-12 14:23 UTC by agmmnn

translate `Extracting State Logic into a Reducer`
https://react.dev/learn/extracting-state-logic-into-a-reducer

2023-05-12 14:28 UTC, agmmnn commented
dispatch'i dağıtmak olarak çevirdim oldu mu bilmiyorum.

2023-05-12 19:16 UTC, alioguzhan requested changes
Hocam eline saglik. Dispatch konusunda, bence `gondermek` daha dogru bir ceviri olur burda. Cunku `store` a bir `action` gonderme soz konusu. 

Emin olamadigim icin biraz arastirdim yine de. Birkac kaynagi birakiyorum buraya:

- https://wikidiff.com/send/dispatch
- https://qr.ae/pyh2Ar

2023-05-16 18:15 UTC, agmmnn commented
gerekli değişiklikler yapıldı. (malum gündem yoğun anca bilgisayar başına geçebildim)

2023-05-16 20:33 UTC, alioguzhan commented
sorun yok hocam. herkes ayni durumda :) eline saglik.

2023-05-16 20:33 UTC, alioguzhan approved these changes

2023-05-16 20:34 UTC, merged