translate `Updating Arrays in State`
reactjs/tr.react.dev pull request #460
Opened 2023-05-27 14:10 UTC by serkanisyapan

`Mutation` kelimesini `Updating Objects in State `  çevirisindeki gibi `mutasyona uğratmak` olarak çevirdim. Görüşlerinizi bekliyorum.

2023-06-03 14:50 UTC, baspinarenes commented
"mutable" ve "immutable" kelimeleri neredeyse tüm Türkçe kaynaklarda "değiştirilebilir" ve "değiştirilemez" olarak kullanılıyor. Genel kabule uymamız gerektiğini düşünüyorum. @alioguzhan abi ne diyorsun bu duruma?

2023-06-03 15:19 UTC, serkanisyapan commented
"değiştirilebilir" ve "değiştirilemez"  olarak çevirince bazı yerlerde çok karışıklığa neden oluyor sanki. "change" gibi kelimelerle bir arada kullanıldığı yerlerde özellikle.

2023-06-03 15:42 UTC, baspinarenes requested changes

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +JavaScript'te diziler de bir tür nesnedir. [Nesnelerde olduğu gibi](/learn/updating-objects-in-state), **React state'indeki dizileri salt okunur olarak görmelisiniz.** Bu, `arr[0] = 'bird'` şeklinde
```suggestion
JavaScript'te diziler bir nesne türüdür. [Nesnelerde olduğu gibi](/learn/updating-objects-in-state), **React state'indeki dizileri salt okunur olarak görmelisiniz.** Bu, `arr[0] = 'bird'` şeklinde bir dizi içindeki öğeleri başka değerlere yeniden atamamanız, `push()` ve `pop()` gibi dizileri mutasyona uğratan JavaScript metodlarını kullanmamanız gerektiği anlamına gelir.
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +Alternatif olarak, her iki sütundaki metodları kullanmanıza izin veren [Immer'ı] (#write-concise-update-logic-with-immer) tercih edebilirsiniz.
```suggestion
Alternatif olarak, her iki sütundaki metodları kullanmanıza izin veren [Immer'ı](#write-concise-update-logic-with-immer) tercih edebilirsiniz.
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +### Bir diziye eklemek {/*adding-to-an-array*/}
```suggestion
### Diziye öğe ekleme {/*adding-to-an-array*/}
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +`push()` metodu diziyi mutasyona uğratacaktır ancak biz bunu istemiyoruz.
React dökümanının genel kuralı sizli konuşmak. Biz dilini kullanmamamız lazım:

```suggestion
`push()` metodu diziyi mutasyona uğratacaktır, ki bunu istemezsiniz:
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +Bunun yerine, mevcut öğeleri *ve* dizinin son elemanı olarak yeni öğeyi içeren *yeni* diziyi oluşturun. Bunu yapmanın birden çok yolu vardır ancak en kolay yol `...` [dizi spread](https://developer.m
```suggestion
Bunun yerine, mevcut öğeleri *ve* son eleman olarak yeni öğeyi içeren *yeni* diziyi oluşturun. Bunu yapmanın birden çok yolu vardır ancak en kolay yol `...` [dizi spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_array_literals) sözdizimini kullanmaktır:
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +    { id: nextId++, name: name } // ve dizinin sonuna eklenecek yeni öğe
```suggestion
setArtists( // State'i yeni bir dizi 
  [ // ile değiştirin.
    ...artists, // Bu eski öğelerin tümünü
    { id: nextId++, name: name } // ve sona eklenecek yeni öğeyi içerir.
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +### Bir diziden çıkartmak {/*removing-from-an-array*/}
```suggestion
### Diziden öğe çıkartma {/*removing-from-an-array*/}
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +Diziden bir öğeyi çıkartmanın en kolay yolu o öğeyi *filtrelemek'tir.* Bir başka deyişle, o öğeyi içermeyen yeni bir dizi oluşturmaktır. Bunu yapmak için `filter` metodunu kullanabilirsiniz. Örneğin:
```suggestion
Diziden bir öğeyi çıkartmanın en kolay yolu o öğeyi *filtrelemektir.* Bir başka deyişle, o öğeyi içermeyen yeni bir dizi oluşturmaktır. Bunu yapmak için `filter` metodunu kullanabilirsiniz. Örneğin:
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +Burada `artists.filter(a => a.id !== artist.id)` ifadesi "ID'leri `artist.id`'den farklı olan `artists`'den oluşan yeni bir dizi oluştur" anlamına gelmektedir. Diğer bir deyişle, her bir artist'e kar
```suggestion
Burada `artists.filter(a => a.id !== artist.id)` ifadesi "`artists` dizisini kullanarak ID'leri `artist.id`'den farklı olan öğelerle yeni bir dizi oluştur" anlamına gelmektedir. Diğer bir deyişle, her bir artist'e karşılık gelen "Sil" butonu o artist'i diziden filtreleyecek ve nihai dizi ile yeniden render isteği gönderecektir. `filter` metodunun orijinal diziyi değiştirmediğini unutmayın.
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +### Bir diziyi dönüştürmek {/*transforming-an-array*/}
```suggestion
### Diziyi dönüştürme {/*transforming-an-array*/}
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +Eğer dizideki bazı ya da tüm öğeleri değiştirmek isterseniz **yeni** bir dizi oluşturmak için `map()` metodunu kullanabilirsiniz. `map`'e ileteceğiniz fonksiyon, verisine veya indeksine (veya her iki
```suggestion
Dizideki bazı ya da tüm öğeleri değiştirmek isterseniz **yeni** bir dizi oluşturmak için `map()` metodunu kullanabilirsiniz. `map`'e ileteceğiniz fonksiyon, verisine veya indeksine (veya her ikisine) bağlı olarak her bir öğeyle ne yapacağınızı belirler.
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +### Bir dizideki öğeleri değiştirmek {/*replacing-items-in-an-array*/}
```suggestion
### Dizideki öğeleri değiştirme {/*replacing-items-in-an-array*/}
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +### Dizide belli bir konuma eklemek {/*inserting-into-an-array*/}
```suggestion
### Dizideki belirli konuma öğe ekleme {/*inserting-into-an-array*/}
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +Bazen bir öğeyi ne dizinin başına ne de dizinin sonuna değil de belirlediğiniz başka bir konuma eklemek isteyebilirsiniz. Bunu yapmak için, `...` dizi spread sözdizimini `slice()` metodu ile beraber
```suggestion
Bazen bir öğeyi dizinin başına ya da sonuna değil de belirli bir bir konuma eklemek isteyebilirsiniz. Bunu yapmak için, `...` dizi spread sözdizimini `slice()` metodu ile beraber kullanabilirsiniz. `slice()` metodu diziden bir "dilim (slice)" almanızı sağlar. Yeni öğeyi eklemek için, eklemek istediğiniz konumdan önceki dilimden spread sözdizimi ile yeni bir dizi oluşturacak, ardından yeni öğeyi ekleyecek ve son olarak da orijinal dizinin geri kalanını ekleyeceksiniz.
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +Bu örnekte, Ekle butonu her zaman `1` indeksinde ekler:
```suggestion
Bu örnekte, Ekle butonu her zaman `1.` indekse ekler:
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +### Bir dizide başka değişiklikler yapmak {/*making-other-changes-to-an-array*/}
```suggestion
### Dizide başka değişiklikler yapma {/*making-other-changes-to-an-array*/}
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +Spread sözdizimi, `map()` ve `filter()` metodları gibi diziyi mutasyona uğratmayan yöntemlerle yapamayacağınız bazı şeyler vardır. Örneğin, bir diziyi sıralamak veya dizi öğelerini ters çevirmek iste
```suggestion
Spread sözdizimi veya `map()` ve `filter()` gibi diziyi mutasyona uğratmayan metodlarla yapamayacağınız bazı şeyler vardır. Örneğin, bir diziyi sıralamak veya dizi öğelerini ters çevirmek isteyebilirsiniz. JavaScript'in `reverse()` ve `sort()` metodları orijinal diziyi değiştirir, bu nedenle doğrudan kullanamazsınız.
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +## Dizi içindeki nesneleri güncelleme {/*updating-objects-inside-arrays*/}
```suggestion
## Dizideki nesneleri güncelleme {/*updating-objects-inside-arrays*/}
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +Nesneler dizilerin  _gerçekten_ "içinde" değillerdir. Yazdığınız kodda "içeride" olarak görünebilir ancak bir dizideki her nesne, dizinin "işaret ettiği" ayrı bir değerdir. Bu yüzden `list[0]` gibi i
```suggestion
Nesneler  _gerçekte_ dizilerin "içinde" yer almazlar. Yazdığınız kodda "içinde" gibi görünebilir ancak bir dizideki her nesne, dizinin "işaret ettiği" ayrı bir değerdir. Bu yüzden `list[0]` gibi iç içe ifadeleri değiştirirken dikkatli olmalısınız. Başka bir kişinin sanat eseri listesi (artwork list), dizinin aynı öğesine işaret edebilir!
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +Bu örnekte, iki farklı sanat eseri listesi aynı ilk state'e (initialList) sahiptir. Bu listelerin izole olmaları gerekirdi ancak bir mutasyon nedeniyle yanlışlıkla state'leri paylaşmaktadırlar ve lis
```suggestion
Bu örnekte, iki farklı sanat eseri listesi aynı başlangıç state'ine sahiptir. Bu listelerin izole olmaları gerekirdi ancak bir mutasyon nedeniyle yanlışlıkla state'leri paylaşmaktadırlar ve listedeki bir kutuyu işaretlemek diğer listeyi de etkilemektedir:
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +`handleIncreaseClick` fonksiyonunun mantığını yazın ki "+" butonuna tıklandığında ürünün sepetteki sayısı artsın:
```suggestion
"+" butonuna tıklandığında ilgili sayının artması için `handleIncreaseClick` mantığını doldurun:
```

2023-06-03 15:42 UTC, baspinarenes commented on src/content/learn/updating-arrays-in-state.md
> +Bu örnekle bir önceki örnek aynıdır. Bu sefer mutasyonları Immer kullanarak düzelteceğiz. `useImmer` halihazırda import edilmiştir, yani kullanmak için `todos` state değişkenini değiştirmeniz gerekme
```suggestion
Bu örnekle bir önceki örnek aynıdır.  Bu sefer Immer kullanarak mutasyonları düzeltin. Kolaylık sağlaması için, `useImmer` halihazırda içe aktarılmıştır. Bunu kullanarak`todos` state değişkenini değiştirmeniz gerekir.
```

2023-06-03 15:46 UTC, baspinarenes commented
> "değiştirilebilir" ve "değiştirilemez" olarak çevirince bazı yerlerde çok karışıklığa neden oluyor sanki. "change" gibi kelimelerle bir arada kullanıldığı yerlerde özellikle.

Şu ana kadar kullanılan hiçbir içerikte kafa karıştırdığı duruma rastlamadım açıkcası. Bir kelime bizim dilimizde birden çok anlama geliyor diye hepsinde farklı kullanmamıza gerek yok. Hepsini kendi bağlamında değerlendirebiliriz.

2023-06-03 17:02 UTC, alioguzhan commented
kelimelerin direkt anlami `degisebilir` ve `degismez` seklinde. Ama programlama baglaminda `degistirilebilir` ve `degistirilemez` bence uygun. Zaten eski sitedeki cevirilerde de bu sekilde cevirmis olmamiz lazim. Bu konunun ya da `mutability` ye dair diger konularin basliklarina https://tr.reactjs.org sitesinden bakilabilir. @serkanisyapan @baspinarenes

2023-06-03 17:23 UTC, serkanisyapan commented
Önceden başka bir kelime için kullanmıştım eski çeviriyi, bu sefer aklıma gelmedi nedense 😃. Değişiklikleri yaparım bu gece. Teşekkürler @alioguzhan @baspinarenes

2023-06-03 17:45 UTC, alioguzhan commented
@serkanisyapan eyvallah hocam. elinize saglik simdiden :)

2023-06-06 06:12 UTC, baspinarenes approved these changes

2023-06-06 06:13 UTC, merged