translate you-might-not-need-an-Effect
reactjs/tr.react.dev pull request #469
Opened 2023-06-15 18:58 UTC by enesakkose

2023-06-17 11:18 UTC, alioguzhan requested changes
Tesekkurler. Elinize saglik. Genel olarak guzel bir ceviri olmus. Degisiklik yapilmasi gereken yerleri belirttim. Sonrasinda merge edebiliriz.

2023-06-17 11:18 UTC, alioguzhan commented on src/content/learn/you-might-not-need-an-effect.md
> +Genelde, ne zaman Efektleri yazmak zorunda kaldığınızda, `useData` gibi daha deklaratif ve amaç odaklı bir API'ye sahip olan özel bir Hook'a bir işlevselliği çıkarabileceğiniz durumları gözlemleyin.
`ne zaman Efektleri yazmak zorunda kaldığınızda` kismi icin :

- ne zaman Efekt yazmak zorunda kalsaniz
- her Efekt yazmak zorunda kaldığınızda

ikisinden biri daha dogru olur gibi duruyor.

2023-06-17 11:18 UTC, alioguzhan commented on src/content/learn/you-might-not-need-an-effect.md
> +#### Efektler olmadan state'i sıfırla {/*reset-state-without-effects*/}
`sifirlayin` diyebiliriz buraya. genelde cogul sekilde yapilmis ceviri cunku.

2023-06-17 11:18 UTC, alioguzhan commented on src/content/learn/you-might-not-need-an-effect.md
> +Kullanıcının "Thank you" iletişim kutusunu görmesi _nedeniyle_ mesaj gönderilmeli mi? Yoksa tam tersi mi geçerlidir?
Bu daha anlasilir olabilir:

`Kullanıcı "Thank you" mesajını _gördüğü için_ mi mesaj gönderilmeli? Yoksa tam tersi, mesajı gönderdiği için mi "Thank You" mesajını görmeli?`

2023-06-17 11:18 UTC, alioguzhan commented on src/content/learn/you-might-not-need-an-effect.md
> +Uygulamanızın kullanıcıları çok fazla mesaj gönderiyor. Sohbet etmeyi biraz daha zorlaştırmak için, form yerine *önce* "Thank you" iletişim kutusunu göstermeye karar verdiniz. Bunun için `showForm` s
`iletişim kutusu` yerine `mesaj` diyebiliz burada bence. ya da `bildirim mesajı`.

2023-06-17 11:18 UTC, alioguzhan commented on src/content/learn/you-might-not-need-an-effect.md
> +`showForm` state değişkeni formun veya "Thank you" iletişim kutusunun gösteriliğ gösterilmeyeceğine karar verir. Ancak "Thank you" iletişim kutusu _görüntülendiği_ için mesajı gönderemiyorsunuz. Kull
Ilk cumle: 

`showForm` state değişkeni, formun mu yoksa "Thank you" mesajının mı gösterileceğini belirler.  

bir de:

 `gönderemiyorsunuz` -> `göndermiyorsunuz`

2023-06-18 14:39 UTC, alioguzhan approved these changes
Tesekkurler. Merge ediyorum.

2023-06-18 14:39 UTC, merged

2023-06-18 15:11 UTC, enesakkose commented
Rica ederim.