translate passing data deeply with context
reactjs/tr.react.dev pull request #472
Opened 2023-07-02 13:48 UTC by Rogultum

teşekkürler.
istediğiniz değişiklikler varsa yapabilirim.

2023-07-15 12:30 UTC, baspinarenes requested changes

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +2. **Elemanları çıkarın ve [JSX'i alt eleman olarak aktarın](/learn/passing-props-to-a-component#passing-jsx-as-children) to them.** Eğer bir veriyi, onu kullanmayan bir kaç katmandan (ortanca eleman
```suggestion
1. **[Prop olarak aktararak](/learn/passing-props-to-a-component) başlayın.** Eğer küçük bileşenleriniz yoksa, bir düzine bileşen için bir düzine prop aktarmak olağandışı bir durum değildir. Zahmetli gibi görünebilir ancak hangi bileşenlerin hangi veriyi kullandığını çok net bir şekilde gösterir! Kodunuzun bakımını yapan kişi, veri akışını prop'lar ile açık bir şekilde belirttiğiniz için size minnettar olacaktır.
2. **Bileşenlere ayırın ve [JSX'i `children` olarak aktarın](/learn/passing-props-to-a-component#passing-jsx-as-children).** Bazı verileri, bu veriyi kullanmayan (yalnızca aşağıya aktaran) birçok ara bileşen katmanından geçirmeniz gerekiyorsa, genellikle bileşene çıkarmayı unutmuş unttuğunuz kodlarınızın olduğu anlamına gelir. Örneğin, `posts` gibi veri prop'larını o veriyi direkt kullanmayan görsel bileşenlere aktarıyor olabilirsiniz, mesela `<Layout posts={posts} />`. Bunun yerine, `Layout`'un alt bileşenini `children` olarak almasını sağlayın ve `<Layout><Posts posts={posts} /></Layout>` olarak render edin. Bu kullanım, veriyi sağlayan ile veriye ihtiyaç duyan bileşenler arasındaki katman sayısını azaltır.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +* **Tema:** Eğer uygulamanız kullanıcıya görünümü değiştirme olanağı veriyorsa (mesela karanlık mod), uygulamanızın en tepesine, context sağlayıcı yerleştirebilirsiniz, ve bu context'i görünümlerini
```suggestion
* **Tema:** Uygulamanız kullanıcının görünümü değiştirmesine izin veriyorsa (mesela karanlık mod), uygulamanızın en üstüne bir context provider koyabilir ve bu context'i görsel görünümlerini değiştirmesi gereken bileşenlerde kullanabilirsiniz.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +* **Çevrimiçi hesap:** Bir çok eleman o an çevrimiçi olan hesap hakkında işlem yapıyor olabilir. Bu bilgiyi context'e koymak uygulamanızın herhangi bir yerinden ona ulaşmanız için kolaylık sağlar. Ba
```suggestion
* **Çevrimiçi hesap:** Bir çok bileşenin o anda oturum açmış olan kullanıcıyı bilmesi gerekebilir. Bunu bir context'e yerleştirmek, ağacın herhangi bir yerinde okumayı kolaylaştırır. Bazı uygulamalar aynı anda birden fazla hesabı çalıştırmanıza da izin verir (örneğin, farklı bir kullanıcı olarak yorum bırakmak için). Bu gibi durumlarda, kullanıcı arayüzünün bir kısmını farklı geçerli kullanıcıya sahip provider'a sarmalamak uygun olabilir.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +* **Routing:** Çoğu "router", mevcut rotayı tutmak için içeriden context kullanır. Bu şekilde, linkler aktif olup olmadığını "bilir". Eğer kendi router sisteminizi oluşturuyorsanız, siz de bunu yapma
```suggestion
* **Routing:** Çoğu routing çözümü, geçerli yolu tutmak için dahili olarak context kullanır. Linkler aktif olup olmadığını bu şekilde "bilir". Kendi yönlendiricinizi oluşturuyorsanız, siz de bunu yapmak isteyebilirsiniz.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +* **State yönetimi:** Uygulamanız büyüdükçe, state'lerinizin birçoğu uygulamanızın üst kısmında kalabilir. Altta bulunan uzak elemanlar bu state'leri değiştirmek isteyebilir. Bu tür durumlarda [conte
```suggestion
* **State yönetimi:** Uygulamanız büyüdükçe, uygulamanızın üst kısmına yakın çok sayıda state ile karşılaşabilirsiniz. Farklı derinlikteki birçok bileşen bunları değiştirmek isteyebilir. Karmaşık state'leri yönetmek ve çok fazla güçlük çekmeden uzaktaki bileşenlere aktarmak için [context ile birlikte bir reducer kullanmak](/learn/scaling-up-with-reducer-and-context) yaygındır.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +Context kullanımı statik değerler ile sınırlı değildir. Eğer bir sonraki render işlemi sırasında farklı bir değer aktarırsanız, React bu değeri okuyan bütün elemanları günceller! Bu nedenle context g
```suggestion
Context kullanımı, statik değerlerle sınırlı değildir. Bir sonraki render'da farklı bir değer iletirseniz, React onu okuyan tüm bileşenleri günceller! Bu yüzden context genellikle state ile birlikte kullanılır.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +Genellikle, eğer bir bilgiye ağacın farklı yerlerinde bulunan uzak elemanlar tarafından ihtiyaç duyuluyorsa, bu durum context'in işinize yarayacağına dair güzel bir göstergedir.
```suggestion
Genellikle, bazı bilgilere ağacın farklı bölümlerindeki bileşenler tarafından ihtiyaç duyulması, context'in işinize yarayacağına dair güzel bir göstergedir.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +* Context bir elemanın altındaki tüm ağaca bilgi aktarmasını sağlar.
```suggestion
* Context, bir elemanın altındaki tüm ağaca bilgi aktarmasını sağlar.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +  1. Şu şekilde oluşturun ve export edin: `export const MyContext = createContext(defaultValue)`.
```suggestion
  1. `export const MyContext = createContext(defaultValue)` ile oluşturun ve dışa aktarın.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +  2. `useContext(MyContext)` Hook'unu kullanarak, ne kadar derinde olursa olsun, herhangi bir alt elemanda context'i okuyabilirsiniz..
```suggestion
  2. Farklı derinlikteki herhangi bir alt bileşenden okumak için `useContext(MyContext)` Hook'una aktarın.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +  3. Üst elemandan onu aktarmak için, alt elemanları şu şekilde sarın: `<MyContext.Provider value={...}>`.
```suggestion
  3. Üst bileşenden değer sağlamak için, alt bileşenleri `<MyContext.Provider value={...}>` içine sarın.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +* Context ortada bulunan herhangi bir elamandan "geçer".
```suggestion
* Context ortada bulunan herhangi bir elamandan aktarılır.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +* Context, "çevresine uyum sağlayabilen" elemanlar yazmanıza olanak sağlar.
```suggestion
* Context, "çevresine adapte olan" bileşenler yazmanıza olanak sağlar.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +* Context kullanmadan önce, prop'ları aktarmayı veya JSX'i `children` olarak aktarmayı deneyin.
```suggestion
* Context kullanmadan önce, prop olarak aktarmayı veya JSX'i `children` olarak iletmeyi deneyin.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +#### Context'i prop sondajlaması yerine kullanmak {/*replace-prop-drilling-with-context*/}
```suggestion
#### Prop drilling yerine context kullanmak {/*replace-prop-drilling-with-context*/}
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +Bu örnekte, onay kutusunun (checkbox) işaretini değiştirmek, her bir `<PlaceImage>` elemanına aktarılan imageSize prop'unu değiştirir. Onay kutusunun state'i en üst seviye `App` elemanında tutulur, a
```suggestion
Bu örnekte, onay kutusunun (checkbox) işaretini değiştirmek, her `<PlaceImage>` bileşenine aktarılan `imageSize` prop'unu değiştirir. Onay kutusunun state'i en üst kapsam olan `App` bileşeninde tutulur her `<PlaceImage>`'ın bundan haberdar olması gerekir.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +Şuan, `App` `imageSize` prop'unu `List` elemanına aktarıyor, oradan `Place` elemanına aktarılıyor, oradan `PlaceImage` elemanına aktarılıyor. `imageSize` prop'unu kaldırın, bunun yerine `App` elemanı
```suggestion
Şu anda, `App` `imageSize` değerini `List`'e, `List` de `PlaceImage`'a aktarmaktadır. `imageSize` prop'unu kaldırın ve bunun yerine `App` bileşeninden doğrudan `PlaceImage`'a aktarın.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +Context tanımını şurada yapabilirsiniz: `Context.js`.
```suggestion
Context tanımını `Context.js` dosyasında yapabilirsiniz.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +        Büyük resim kullan
```suggestion
        Büyük resimleri kullan
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +`imageSize` prop'unu bütün elemanlardan kaldırın.
```suggestion
`imageSize` prop'unu bütün bileşenlerden kaldırın.
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +`Context.js`'den `ImageSizeContext`'i oluşturun ve export edin. Ardından değeri aşağı aktarmak için List'i `<ImageSizeContext.Provider value={imageSize}>` tarafından sarın, ve `useContext(ImageSizeCo
```suggestion
`Context.js` dosyasında `ImageSizeContext`'i oluşturun ve dışa aktarın. Ardından değeri aşağı aktarmak için `List`'i `<ImageSizeContext.Provider value={imageSize}>` ile sarın ve `useContext(ImageSizeContext)` kullanarak `PlaceImage` bileşeninde değerini okuyun:
```

2023-07-15 12:30 UTC, baspinarenes commented on src/content/learn/passing-data-deeply-with-context.md
> +Not: Artık ortanca elemanların `imageSize` prop'unu aktarmasına gerek yok.
```suggestion
Not: Artık ara bileşenlere `imageSize` prop'unu iletmeye gerek olmadığına dikkat edin.
```

2023-07-15 12:31 UTC, baspinarenes requested changes
Çeviri genelinde "eleman" kelimesi kullanılmış ancak "bileşen" daha anlamlı olacaktır.

2023-07-15 12:32 UTC, baspinarenes commented
İşlerdeki yoğunluktan ötürü geç review edebildim kusuruma bakmayın :/

2023-07-15 14:05 UTC, Rogultum commented
Ben sizi çok uğraştırdıysam siz kusuruma bakmayın. :)

2023-07-15 14:15 UTC, Rogultum commented on src/content/learn/passing-data-deeply-with-context.md
> +Genellikle, bilgiyi üst elemandan alt elemana doğru, prop'lar ile aktarırsınız. Ancak, prop'ları aktarırken aşağıya doğru çok fazla ortanca eleman varsa veya geçirdiğiniz bilgiyi uygulamanızda birçok
Şu kısım: "Ancak, aktarmanız gereken bileşen ulaşana kadar birçok ara bileşene iletmeniz veya birden çok bileşene aktarmanız gerekiyorsa prop kullanmak zahmetli ve karmaşık hale gelir." 
Bana biraz karmaşık geldi, şöyle çevirmeye ne dersiniz? 
"Ancak, prop'ları birçok ara bileşenden aşağıya doğru aktarmak veya birden çok bileşende kullanmak zahmetli ve karmaşık hale gelir."

2023-07-16 10:35 UTC, baspinarenes commented
Estafurullah review'ları inceleyip aksiyon aldıktan sonra değişiklikleri merge edebilirim.

2023-08-02 22:47 UTC, alioguzhan approved these changes
Hizlica bir goz gezdirdim. Genel olarak olmus gibi. Eksiklikler varsa da diger insanlar PR cikabilirler. Ya da size merge edildikten sonra tekrar bir kontrol etmek isteyebilirsiniz. Kendiniz de eksiklikler / hatalar gorurseniz yeni bir PR cikabilirsiniz. 

Elinize saglik

2023-08-06 11:28 UTC, baspinarenes approved these changes

2023-08-06 11:29 UTC, merged