translate manipulating the DOM with refs
reactjs/tr.react.dev pull request #485
Opened 2023-08-18 10:10 UTC by dilarauluturhan

2023-08-18 19:26 UTC, alioguzhan requested changes
Ceviri icin tesekkurler. Belirttigim noktalar guncellendikten sonra merge edebiliriz.

2023-08-18 19:26 UTC, alioguzhan commented on src/content/learn/manipulating-the-dom-with-refs.md
> +## React'te Ref'leri Ekleme {/*when-react-attaches-the-refs*/}
Aslinda direkt cevirisi `React refleri eklediginde`. Bunu kullanabiliriz. `React'te Ref'leri Ekleme` tam karsiligi degil. Cunku refleri bizim eklememizle ilgili bir durum aciklanmiyor burada.

Bununla birlikte, daha aciklayici olmasi icin `Ref'lerin eklendigi zaman` ya da `React ref'leri ne zaman ekler` tarzi bir ceviri de uygun olabilir. Size birakiyorum bu kismini.

2023-08-18 19:26 UTC, alioguzhan commented on src/content/learn/manipulating-the-dom-with-refs.md
> +#### flushSync ile Senkronize Durum Güncellemelerini Temizleme {/*flushing-state-updates-synchronously-with-flush-sync*/}
Burada senkronize olan durum guncellemeleri degil aslinda. Temizleme sekli senkron. Dolayisiyla:

`State guncellemelerini flushSync ile senkronize bir sekilde temizleme`  

daha dogru bir ceviri olabilir.

2023-08-18 19:26 UTC, alioguzhan commented on src/content/learn/manipulating-the-dom-with-refs.md
> +#### Carousel Kaydırma {/*scrolling-an-image-carousel*/}
Carousel baska yerlerde de kullanilmis. Cevirip cevirmeme konusunda kararsizim aslinda. `Resim Galerisi` diyebiliriz. Teknik olarak yanlis sayilmaz. Onun disinda bu satirin cevirisi ozelinde, 

`Bir resim galerisini kaydirma` seklinde cevirmek daha dogru olacaktir. Cevirmemeye karar verirseniz de:

`Bir carouseli kaydirma` seklinde olabilir.

2023-09-02 10:49 UTC, dilarauluturhan commented
Belirttiğiniz düzeltmeleri yapıp kontrol ettim ve push'ladım

2023-09-02 11:50 UTC, alioguzhan approved these changes
Tesekkurler. Elinize saglik.

2023-09-02 11:55 UTC, merged

2023-09-02 12:24 UTC, dilarauluturhan commented
Rica ederim, iyi çalışmalar.