feat: translate to lifecycle-of-reactive-effects pages
reactjs/tr.react.dev pull request #490
Opened 2023-09-05 11:43 UTC by burakcihan61

2023-09-05 19:20 UTC, alioguzhan requested changes
Effect -> Efekt
Effects -> Efektler

seklinde ceviriyi guncellersek sonrasinda merge edebiliriz.

2023-09-05 19:20 UTC, alioguzhan commented on src/content/learn/lifecycle-of-reactive-effects.md
> +title: 'Reaktif Effects Yaşam Döngüsü'
Reacktif Efektlerin Yaşam Döngüsü

daha dogru bir ceviri olabilir. Burada da asagida da `effect` kelimesini cevirebiliriz.

2023-09-05 21:14 UTC, burakcihan61 commented on src/content/learn/lifecycle-of-reactive-effects.md
> +title: 'Reaktif Effects Yaşam Döngüsü'
Burada effect kullanmamım sebebi, çeviri kurallarında yazan ortak çeviriler.
https://github.com/reactjs/tr.react.dev/blob/main/TRANSLATION.md
Tekrar düzenleyip gönderiyorum.

2023-09-07 13:10 UTC, alioguzhan commented on src/content/learn/lifecycle-of-reactive-effects.md
> +title: 'Reaktif Effects Yaşam Döngüsü'
Haklisiniz. Ozur dilerim. 2021 yilinda oyle bir karar almisiz. Ben de hatirlamiyordum. Hatta direkt ben dahil olmusum olaya surada: https://github.com/reactjs/tr.react.dev/issues/300

O karari almamiza sebep olan ceviride ozel olarak hook olan efektlerden bahsediliyordu sanirim. Google aramalarinda cikmasi icin oyle tutalim demistik. 

Ama bugun bakinca cevirmek daha mantikli geldi. Bir de buradaki ceviride daha cok konseptin aciklanmasi soz konusu hooklardan ziyade. `TRANSLATION.md` dosyasini da guncelledim. Diger dillere de baktigimda genelde arkadaslar cevirmisler `effect` kelimesini.

2023-09-07 13:10 UTC, alioguzhan approved these changes
Elinize saglik. Merge ediyorum.

2023-09-07 13:14 UTC, merged