translate describing the ui
reactjs/tr.react.dev pull request #530
Opened 2024-02-06 18:24 UTC by TolgaYuceel

Selamlar,

`Describing the UI` sayfasının çevirisini tamamladım. Ancak çeviri sırasında `Describing the UI` kısmı altındaki `Understanding Your UI as a Tree` bölümünün [issue](https://github.com/reactjs/tr.react.dev/issues/397) altında  kontrol listesine eklenmediğini fark ettim, sanırım gözden kaçmış. Eğer isterseniz o bölümü de çevirebilirim.

Kontrol listesine eklenmeyen sayfanın linki: [https://tr.react.dev/learn/understanding-your-ui-as-a-tree](https://tr.react.dev/learn/understanding-your-ui-as-a-tree)

2024-02-06 19:43 UTC, serkanisyapan commented
Evet o sayfa sonradan eklendi sanırım biz eklememişiz. Size verdim o sayfayı da. Bunun review'unu da yapacağım.

2024-02-06 19:49 UTC, TolgaYuceel commented
> Evet o sayfa sonradan eklendi sanırım biz eklememişiz. Size verdim o sayfayı da. Bunun review'unu da yapacağım. Eline sağlık.

Tamamdır, Teşekkürler.

2024-02-07 09:21 UTC, serkanisyapan requested changes
`render` kelimesi `oluşturma` olarak çevirilmiş bazı yerlerde. Bir kaç yerin çevirilmesi gözden kaçmış. Düzelttikten sonra merge edelim. Eline sağlık.

2024-02-07 09:21 UTC, serkanisyapan commented on src/content/learn/describing-the-ui.md
> +React render ağacı, bileşenler arasındaki ebeveyn ve çocuk ilişkisinin bir temsilidir.
```suggestion
React render ağacı, bileşenler arasındaki üst ve alt ilişkisinin bir temsilidir.
```
`TRANSLATION.md`'ye göre bu kelimeleri üst/alt olarak çeviriyoruz.

2024-02-07 09:21 UTC, serkanisyapan commented on src/content/learn/describing-the-ui.md
>  <Diagram name="generic_render_tree" height={250} width={500} alt="A tree graph with five nodes, with each node representing a component. The root node is located at the top the tree graph and is labe
burası da gözden kaçmış

2024-02-07 09:21 UTC, serkanisyapan commented on src/content/learn/describing-the-ui.md
> +Ağacın tepesine , kök bileşene yakın bileşenler üst düzey bileşenler olarak kabul edilir. Alt elemanı olmayan bileşenler yaprak bileşenlerdir. Bileşenlerin bu şekilde kategorize edilmesi, veri akışın
```suggestion
Ağacın tepesine, kök bileşene yakın bileşenler üst düzey bileşenler olarak kabul edilir. Alt elemanı olmayan bileşenler yaprak bileşenlerdir. Bileşenlerin bu şekilde kategorize edilmesi, veri akışını ve render etme performansını anlamak için kullanışlıdır.
```
fazla boşluk ve render etme

2024-02-07 09:21 UTC, serkanisyapan commented on src/content/learn/describing-the-ui.md
> +
fazladan whitespace var sanırım burda

2024-02-07 09:21 UTC, serkanisyapan commented on src/content/learn/describing-the-ui.md
>  <Diagram name="generic_dependency_tree" height={250} width={500} alt="A tree graph with five nodes. Each node represents a JavaScript module. The top-most node is labelled 'RootModule.js'. It has thr
burasıda çevirilmeli

2024-02-07 13:32 UTC, TolgaYuceel commented
Evet, bazı yerleri gözden kaçırmışım. İstenilen değişiklikleri tamamladım.

2024-02-07 13:44 UTC, merged