Translate Using Typescript Page
reactjs/tr.react.dev pull request #566
Opened 2024-09-21 21:01 UTC by halilxibrahim

Translate `Using Typescript` Page

2024-09-29 14:57 UTC, halilxibrahim commented
Mr. @serkanisyapan When will you review it ? Best Regards

2024-09-29 15:59 UTC, serkanisyapan commented
Kusura bakma çok zamanım yoktu çok yakında bakacağım. Başka bir sayfaya başlamak istiyorsan başlayabilirsin

2024-09-30 12:09 UTC, halilxibrahim commented
> Kusura bakma çok zamanım yoktu çok yakında bakacağım. Başka bir sayfaya başlamak istiyorsan başlayabilirsin

Hocam hiç sorun değil sadece sizin için sorun olmasın o yüzden bilgilendirmek istedim.

2024-10-09 13:14 UTC, alioguzhan commented
Bunu ben aliyorum @serkanisyapan. En gec yarin review gelmis olur. Beklettik kusura bakmayin @halilxibrahim

2024-10-09 18:03 UTC, serkanisyapan commented
İkinizde kusura bakmayın bu aralar hiç zamanım olmuyor. Çeviri işi çok arka planda kaldı kendi sayfama bile bakamadım doğru düzgün. 1-2 hafta içinde yapacağım bir kaç çeviri. Kolay gelsin herkese

2024-10-11 16:06 UTC, alioguzhan requested changes
Tesekkurler. Iyilestirilebilecek yerleri belirttim. Tekrar uzerinden gecerseniz sonra merge edebiliriz.

2024-10-11 16:06 UTC, alioguzhan commented on src/content/learn/typescript.md
> +Bu rehber, TypeScript’i React ile kullanmanın temellerini kapsadı, ancak öğrenilecek daha çok şey var. Dokümanlardaki bireysel API sayfaları, TypeScript ile nasıl kullanılacağına dair daha derinlemes
`Bu rehberde TypeScript'i React ile kullanmanın temelleri ele alındı` daha bir ceviri olabilir.

2024-10-11 16:06 UTC, alioguzhan commented on src/content/learn/typescript.md
> + - [TypeScript el kitabu](https://www.typescriptlang.org/docs/handbook/) TypeScript için resmi belgelerdir ve çoğu ana dil özelliğini kapsar.
- typo `u` -> `i`.
- `kapsar` -> `ele alir` ya da `deginir`. daha iyi olabilir.

2024-10-14 13:33 UTC, alioguzhan approved these changes
Tesekkurler!

2024-10-14 14:23 UTC, merged

2024-10-14 17:26 UTC, halilxibrahim commented
@alioguzhan  Hocam şöyle bir hata var gözümüzden kaçmış düzeltip yine bu branch push atıyım mı ? <img width="923" alt="Ekran Resmi 2024-10-14 20 25 43" src="https://github.com/user-attachments/assets/e77ef391-d11c-435d-9e50-372ea9dc45e2">

2024-10-15 11:59 UTC, alioguzhan commented
olur hocam buraya pushlayabilirsin tekrar. merge ederiz buradan. @halilxibrahim

2024-10-15 14:38 UTC, halilxibrahim commented
Hocam  pushladım ama yeni pr açmak durumunda kaldım pr: https://github.com/reactjs/tr.react.dev/pull/571 bakarsanız sevinirim. Aksaklık için kusura bakmayın yeniden.

2024-10-15 15:58 UTC, alioguzhan commented
Ne demek. elinize saglik.