Translate `Reusing Logic With Custom Hooks`
reactjs/tr.react.dev pull request #579
Opened 2024-12-01 21:54 UTC by andyanday33

2024-12-01 21:56 UTC, andyanday33 commented
Oops, eski bir çeviri kalmış sorry, çözüyorum

2024-12-04 13:09 UTC, serkanisyapan requested changes
Gerekli yerleri düzelttikten sonra merge edelim. Elinize sağlık

2024-12-04 13:09 UTC, serkanisyapan commented on src/content/learn/reusing-logic-with-custom-hooks.md
> +Bu Efekt'in cleanup'a ihtiyacı *olmadığını* unutmayın. Eğer cleanup fonksiyonunda `clearTimeout`'u çağırdıysanız, o zaman her `value` değiştiğinde, zaten planlanmış olan timeout'u sıfırlar.  Hareketi
```suggestion
Bu Efekt'in temizleme fonksiyonuna ihtiyacı *olmadığını* unutmayın. Eğer temizleme fonksiyonunda `clearTimeout`'u çağırdıysanız, o zaman her `value` değiştiğinde, zaten planlanmış olan timeout'u sıfırlar.  Hareketi sürekli tutmak için, tüm timeout'ların çalışmasını istersiniz.
```

2025-01-13 08:31 UTC, alioguzhan commented
@serkanisyapan uzun bir sure gecmis sanirim. Istersen PR'i kapatip assignmenti baskasina verebiliriz.

2025-01-13 08:33 UTC, anilcanboga commented
Gerekli düzenlemeler eklenip, çeviri yapılmıştır. @alioguzhan @serkanisyapan

2025-01-13 08:33 UTC, closed without merging